version: "3.9"

services:
  # --------------------- MongoDB ---------------------
  mongodb:
    image: mongo:latest
    container_name: fluimap_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      # Persistência de dados (ajuste se quiser outro path)
      - ./mongo_data:/data/db
    # Se preferir usar /mnt/mongo_data do host, basta trocar:
    # - /mnt/mongo_data:/data/db

  # --------------------- Next.js (FluiMap) ---------------------
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fluimap_web
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      # Apenas exemplos de variáveis obrigatórias.
      # O .env deve conter mais chaves, mas certifique-se de ter essas aqui:
      - DATABASE_URL=${DATABASE_URL}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
    # Se houver outras variáveis (NEXT_PUBLIC_..., etc), inclua-as no .env e aqui.
