version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      # tudo que o Mongo gravar em /data/db no container vai para /mnt/mongo_data no volume raiz.
      # Isso permite persistência de dados mesmo se o container for removido.
      - /mnt/mongo_data:/data/db
